logging:
  config: classpath:logback-conf.xml
spring:
  thymeleaf:
    cache: false
---
spring:
  profiles: dev
server:
  port: 8080
  servlet:
    context-path: /
---
spring:
  profiles: prod
server:
  port: 8081
  servlet:
    context-path: /